print('Hello, Welcome to time difference of two in digtial time')
time1hour = input('Enter the hour of the 1st time: ')
time1min = input('Now enter the minutes: ')
time2hour = input('Enter the hour of the 2nd time: ')
time2min = input('Now enter the minutes: ')
int(time1hour)
int(time1min)
int(time2hour)
int(time2min)
print('The 1st time is: ' + time1hour + ' hours and ' + time1min + " minutes")
print('The 1st time is: ' + time2hour + ' hours and ' + time2min + " minutes")
print("Now is comparing...")
timehour = (int)(time1hour) - (int)(time2hour)
timemins = (int)(time1min) - (int)(time2min)
print("Hours and minutes from: ", time1hour, ":", time1min, " to ", time2hour,  ":" ,time2min, "is:", timehour, "hours and", timemins, "minutes.")